### Register
POST http://localhost:5005/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "testuser01",
    "password": "test123"
}

### Login
POST http://localhost:5005/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "testuser01",
    "password": "test123"
}

### Logout
POST http://localhost:5005/auth/logout HTTP/1.1
Content-Type: application/json 

{
    "refreshToken": "12fc505edb4e448b5a3fa8d3f91fe519d0930f0a115556e68c2ef9863877a5a962f736f9195eca3d7b7eee6234930316dcacb18fbb1706b462b24b04b42bdbce"

}

### Refresh Token
POST http://localhost:5005/auth/refresh HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "12fc505edb4e448b5a3fa8d3f91fe519d0930f0a115556e68c2ef9863877a5a962f736f9195eca3d7b7eee6234930316dcacb18fbb1706b462b24b04b42bdbce"
}

### Get Todos (with access token)
GET http://localhost:5005/todos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2ODAzNzAzMCwiZXhwIjoxNzY4MDM3OTMwfQ.LD6Ig0_CSpFc2xn4HH-Uv9L7bZdpOl7vRT3-hH7M87w

### Create Todo
POST http://localhost:5005/todos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2ODAzNzAzMCwiZXhwIjoxNzY4MDM3OTMwfQ.LD6Ig0_CSpFc2xn4HH-Uv9L7bZdpOl7vRT3-hH7M87w
Content-Type: application/json

{
    "todo": "Learn JWT authentication"
}

### Update Todo
PUT http://localhost:5005/todos/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2ODAzNzAzMCwiZXhwIjoxNzY4MDM3OTMwfQ.LD6Ig0_CSpFc2xn4HH-Uv9L7bZdpOl7vRT3-hH7M87w
Content-Type: application/json

{
    "todo": "Learn JWT authentication - Updated",
    "completed": true
}

### Delete Todo
DELETE http://localhost:5005/todos/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc2ODAzNzAzMCwiZXhwIjoxNzY4MDM3OTMwfQ.LD6Ig0_CSpFc2xn4HH-Uv9L7bZdpOl7vRT3-hH7M87w